#!/bin/sh
set -e
lb config noauto \
  --distribution trixie \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --archive-areas "main contrib non-free-firmware" \
  --debian-installer none \
  --memtest none \
  --bootappend-live "boot=live components username=preboot hostname=it-preboot locales=en_GB.UTF-8 keyboard-layouts=gb timezone=Europe/London" \
  "${@}"
